# Generated by Django 5.0.2 on 2024-02-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('M', 'Medium'), ('L', 'Low'), ('H', 'High')], default='L', max_length=1),
        ),
    ]
