# Generated by Django 5.0.2 on 2024-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('M', 'Medium'), ('H', 'High'), ('L', 'Low')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
