# Generated by Django 5.0.2 on 2024-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_priority_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Medium')], default='L', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('title', 'user')},
        ),
    ]
