# Generated by Django 5.0.2 on 2024-02-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
