# Generated by Django 5.0.2 on 2024-02-18 15:55

import django.core.validators
import django.db.models.deletion
import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_user_user_type_user_type_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='alarm_on',
            field=models.DateTimeField(validators=[todo.models.validate_start_end_time]),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, default='null', null=True, validators=[todo.models.validate_start_end_time]),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.list'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, validators=[todo.models.validate_start_end_time]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('A', 'Admin'), ('F', 'Free'), ('P', 'Pro')], default='F', max_length=1),
        ),
    ]
