# Generated by Django 5.0.2 on 2024-02-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('M', 'Medium'), ('L', 'Low'), ('H', 'High')], default='L', max_length=1),
        ),
    ]
